version: "3"

tasks:
  install:
    desc: "Install tmux"
    cmds:
      - task: install-tmux
      - task: install-tpm
      - task: configure
  install-tmux:
    cmds:
      - task: :apt-install
        vars:
          PACKAGES: tmux acpi
  install-tpm:
    cmds:
      - mkdir -p ~/.tmux/plugins
      - git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    status:
      - test -d ~/.tmux/plugins/tpm
  configure:
    dir: "tasks/tmux"
    cmds:
      - gomplate -f tmux.conf.template -o ~/.tmux.conf
