version: "3"

tasks:
  install:
    desc: "Install tmux"
    cmds:
      - task: install-tmux
      - task: install-tpm
  install-tmux:
    dir: "tasks/tmux"
    cmds:
      - task: :apt-install
        vars:
          PACKAGES: tmux acpi
      - cp -f tmux.conf ~/.tmux.conf
  install-tpm:
    cmds:
      - mkdir -p ~/.tmux/plugins
      - git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
      - ~/.tmux/plugins/tpm/bin/install_plugins
    status:
      - test -d ~/.tmux/plugins/tpm
