version: "3"

includes:
  base: tasks/base
  kube: tasks/kube
  lang: tasks/lang
  tmux: tasks/tmux
  nvim: tasks/nvim

tasks:
  all:
    desc: "Setup everything"
    cmds:
      - task: base:install
      - task: kube:install
      - task: lang:install
      - task: tmux:install
      - task: nvim:install

  # Test locally with docker
  test:
    interactive: true
    cmds:
      - docker build -t dotfiles:test .
      - docker run -it --rm dotfiles:test

  # Utils to simplify and speed up apt-get installs
  apt-install:
    internal: true
    deps: [apt-update]
    cmds:
      - sudo apt-get install -y {{.PACKAGES}}
    preconditions:
      - test -n "{{.PACKAGES}}"
  apt-update:
    internal: true
    cmds:
      - sudo apt-get update
    run: once
