version: "3"

tasks:
  install:
    desc: "Install base"
    cmds:
      - task: install-pkgs
      - task: install-gomplate
      - task: install-yq
      - task: configure-bash
      - task: configure-ssh
      - task: configure-task
  install-pkgs:
    cmds:
      - task: :apt-install
        vars:
          PACKAGES: bash-completion git jq build-essential cmake openssh-client
  install-gomplate:
    cmds:
      - mkdir -p ~/.local/bin
      - curl -o ~/.local/bin/gomplate -sSL https://github.com/hairyhenderson/gomplate/releases/download/{{.VERSION}}/gomplate_{{OS}}-{{ARCH}}
      - chmod 755 ~/.local/bin/gomplate
      - gomplate --version
    vars:
      VERSION:
        sh: curl -sSL https://api.github.com/repos/hairyhenderson/gomplate/releases/latest | jq -r '.tag_name'
  install-yq:
    cmds:
      - mkdir -p ~/.local/bin
      - curl -o ~/.local/bin/yq -sSL https://github.com/mikefarah/yq/releases/latest/download/yq_{{OS}}_{{ARCH}}
      - chmod 755 ~/.local/bin/yq
      - yq --version
  configure-bash:
    dir: tasks/base
    cmds:
      - mkdir -p ~/.bashrc.d
      - cp -f bashrc ~/.bashrc
      - cp -f bash_profile ~/.bash_profile
  configure-ssh:
    cmds:
      - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
      - |
        if ! ls ~/.ssh/*.pub >/dev/null 2>&1 ; then
          ssh-keygen -t ed25519 -C "$(whoami)@$(hostname)" -f ~/.ssh/id_ed25519
        fi
      - |
        if ! ssh-keygen -F github.com > /dev/null ; then
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        fi
  configure-task:
    cmds:
      - mkdir -p ~/.local/share/bash-completion/completions
      - curl -o ~/.local/share/bash-completion/completions/task.bash -sSL https://raw.githubusercontent.com/go-task/task/main/completion/bash/task.bash
